<a href="https://colab.research.google.com/github/Aspartia/BIGDATA/blob/main/2_gyakorlat_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Big Data algoritmusok és programozás - Python

# 2. gyakorlat

## NumPy

___
NumPy (numpy) - a Python lineáris algebra könyvtára. Azért fontos data science területén, mert szinte minden könyvtára használja a NumPy fő elemeit.

Dokumentáció: [NumPy Manual](https://numpy.org/doc/stable/)

A Numpy nagyon gyors, mivel C könyvtárakhoz kapcsolódik.

A gyakorlaton: a NumPy alapok megtanulása.


_____
### Installálás (amennyiben szükéges)

Anaconda környezetben, NumPy installálása terminál ablakban:
    
    conda install numpy
    
vagy nem Anaconda környezetben:

    pip install numpy
    
Bővebben a telepítésről: [Numpy hivatalos dokumentációja a telepítésről.](https://numpy.org/install/)

___
## NumPy használata

Telepítés után a könyvtár importálása:

In [ ]:
import numpy as np

_____
# Numpy tömbök (Numpy Arrays)

A NumPy tömbök többfélék lehetnek: vektorok (1-D tömb), mátrixok (2-D tömb) és 3 vagy többdimenziós tömbök.

Az 1-D tömbök esetén nincs különbség a sorvektor és az oszlopvektor között.

## NumPy tömbök létrehozása

### Python listából

Tömbök készítése közvetlenül listák vagy listákból álló listák átalakításával:

In [ ]:
lista = [1,2,3]
lista

[1, 2, 3]

In [ ]:
# np.array()
np.array(lista)

array([1, 2, 3])

In [ ]:
print(lista)
print(np.array(lista))

[1, 2, 3]
[1 2 3]


In [ ]:
lista_lista = [[1,2,3],[4,5,6],[7,8,9]]
lista_lista

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(lista_lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# np.mat()
mátrix = np.mat('1 2 3; 4 5 6; 7 8 9')
mátrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
sokszínű_lista = [1, 'a', 1.1, "xyzaaaaaaaaaaaaaaa"]

In [ ]:
# A tömb elemei azonos típusúak (array dtype).
sokszínű = np.array(sokszínű_lista)
sokszínű = np.array(sokszínű_lista, dtype= list)

## Beépített módszerek numpy tömbök létrehozására

Sokféleképpen generálhatunk tömböt.

### arange

Egyenletesen elosztott értékek megadása egy adott intervallumon belül.

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# tömb létrehozása 2 és 10 között minden 2. elemmel
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

### zeros, ones

Tömbök generálása 0 - `np.zeros()` vagy 1 - `np.ones()` elemekkel.

In [ ]:
np.zeros(3)

In [ ]:
np.zeros((5,5))

In [ ]:
# tömb elemei legyenek egész számok
np.ones(5, dtype= int)

array([1, 1, 1, 1, 1])

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

In [ ]:
# tömb legyen (2,3,4) dimenziós és elemei egész számok
np.ones((2,3,4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

# empty

Üres tömb létrehozása. Az `empty` függvény létrehoz egy tömböt, amelynek kezdeti tartalma véletlenszerű, a memória állapotától függ. Az `empty` használatának (`zeros` helyett) jelentősége a sebesség - később nem szabad elfeledkezni az összes konkrét elem feltöltéséről!

In [ ]:
üres = np.empty((2,2))
üres

array([[0., 0.],
       [0., 0.]])

Kódrészletek végrehajtási idejének mérése: `timeit`
https://docs.python.org/3/library/timeit.html

In [ ]:
import timeit
print("zeros: ",timeit.timeit("numpy.zeros((100,100))",setup="import numpy"))
print("empty: ",timeit.timeit("numpy.empty((100,100))",setup="import numpy"))

zeros:  2.1892935609999995
empty:  0.3625402629999144


### linspace

Egyenletesen elosztott számok megadása egy meghatározott intervallumon belül.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
# 10 és 100 között 10 szám kiírása, egész számokkal
np.linspace(10,100,10, dtype= int)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### eye

Egységmátrix készítése.

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Készítsük el a következő mátrixot az `eye` függvény segítségével:
```python
array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])
```

In [ ]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

_____
## Véletlen számokból álló tömbök

A Numpy-ban sokféle lehetőség van véletlen tömbök készítésére:

### rand
Létrehoz egy megadott méretű tömböt és ``[0, 1)`` feletti egyenletes eloszlás szerinti véletlen értékekkel feltölti.

In [ ]:
np.random.rand(2)

array([0.44195644, 0.49326749])

In [ ]:
np.random.rand(5,5)

array([[0.91325966, 0.98397589, 0.45765229, 0.80529342, 0.66800397],
       [0.57251041, 0.96906375, 0.28375229, 0.63396018, 0.04220787],
       [0.85019102, 0.65441827, 0.16502835, 0.25392278, 0.80368522],
       [0.01265935, 0.01802143, 0.24853   , 0.88334102, 0.55906718],
       [0.04605406, 0.35480185, 0.38803405, 0.58278508, 0.38511465]])

### randn

Standard normál eloszlás szerinti értékekkel tölti fel a tömböt.

In [ ]:
np.random.randn(2)

array([-0.61578274,  1.25988392])

In [ ]:
np.random.randn(5,5)

array([[-0.75247618,  0.12512146, -0.34004123,  0.42410421, -0.87251226],
       [ 1.7633347 , -1.60776312, -1.8286811 ,  1.25538849, -1.28969584],
       [-1.10945225, -0.13719834, -0.65834413,  1.0203098 ,  0.95513824],
       [ 0.78627198,  0.31335624, -1.02209085, -0.92542093,  0.94455806],
       [-0.72418488,  1.83395237,  0.17234519, -0.30115835, -0.28111148]])

### randint
Véletlen egész értékekkel tér vissza `low` (inclusive) és `high` (exclusive) intervallumból.

In [ ]:
np.random.randint(1,100)

20

In [ ]:
np.random.randint(1,100,10)

array([43, 41,  5, 72, 52, 75,  8,  9, 78, 35])

In [ ]:
np.random.randint(1,100,(10,10))

array([[72, 34, 66, 42, 46, 34, 74, 28, 99, 15],
       [16, 53, 18, 11, 32, 60, 60, 25, 50, 83],
       [67, 12, 68, 39, 56, 54, 14, 26, 22, 88],
       [73, 79, 29, 41, 89, 93, 35, 21, 30,  8],
       [13, 94, 19, 97, 67, 15, 21, 33, 85, 94],
       [17, 25, 78, 30, 83, 73, 35, 53, 41, 58],
       [90, 87, 38, 32, 86,  1,  3, 68, 90, 64],
       [39, 50, 23, 59, 30, 57, 42, 80, 46, 76],
       [13, 79, 27, 54, 38, 36, 11,  3, 25, 23],
       [42, 48, 45, 37, 99,  9, 48,  5, 96, 16]])

_____
## Tömb elemeinek rendezése, hozzáadása, törlése

### sort

In [ ]:
rendezetlen = np.random.randint(1,100,10)
rendezetlen

array([83, 92,  6, 35, 55, 57, 24, 12, 78, 44])

In [ ]:
rendezett = np.sort(rendezetlen)
rendezett

array([ 6, 12, 24, 35, 44, 55, 57, 78, 83, 92])

### concatenate

In [ ]:
np.concatenate(([1,2],[3,4,5]))

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([[5, 10],[15, 20]])
b = np.array([[25, 30]])
print(a,'\n')
print(b)

[[ 5 10]
 [15 20]] 

[[25 30]]


In [ ]:
np.concatenate((a,b))

array([[ 5, 10],
       [15, 20],
       [25, 30]])

Fűzzük össze az `a` és `b` tömböket, hogy az eredmény
```python
array([[ 5, 10, 25],
       [15, 20, 30]])
```
legyen!

In [ ]:
np.concatenate((a,b.T), axis =1)

array([[ 5, 10, 25],
       [15, 20, 30]])

In [ ]:
np.concatenate((a,b), axis=0)

array([[ 5, 10],
       [15, 20],
       [25, 30]])

In [ ]:
np.concatenate((a,b),axis=None)

array([ 5, 10, 15, 20, 25, 30])

### insert
Értékek elhelyezése az adott tengely mentén a megadott indexek elé.

In [ ]:
a

array([[ 5, 10],
       [15, 20]])

In [ ]:
np.insert(a,1,100)

array([  5, 100,  10,  15,  20])

In [ ]:
np.insert(a,1,100,axis=0)

array([[  5,  10],
       [100, 100],
       [ 15,  20]])

In [ ]:
np.insert(a,1,100,axis=1)

array([[  5, 100,  10],
       [ 15, 100,  20]])

Szúrjuk be az `a` tömb elejére és végére a `100, 200` elemekből álló oszlopvektort.

In [ ]:
np.insert( a ,2,[[100,200]], axis=1)
# ezt ne mtudom

array([[  5,  10, 100],
       [ 15,  20, 200]])

In [ ]:
np.insert(a,1,[[100,200],[300,400]],axis=1)

array([[  5, 100, 300,  10],
       [ 15, 200, 400,  20]])

### Eltávolítás
Az elemek tömbből való eltávolításának egyszerű módja a megtartandó elemek indexeléssel történő kiválasztása. (Később)

_____
## Tömbfüggvények

In [ ]:
arr = np.arange(20)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
ranarr

array([16, 21, 42, 10, 27, 11, 31, 30, 37, 18])

### reshape
Egy tömböt ad vissza, amely ugyanazokat az adatokat tartalmazza, új alakban.

In [ ]:
np.reshape(arr,(10,2)) # 20 van benne és ne mfér el 10-be egy

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [ ]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### max, min, argmax, argmin

Hasznos módszerek a maximum vagy a minimum értékek megállapításához, továbbá megtalálni az index értékét az `argmin` vagy az `argmax` segítségével.

In [ ]:
ranarr

array([16, 21, 42, 10, 27, 11, 31, 30, 37, 18])

In [ ]:
ranarr.max()

42

In [ ]:
ranarr.argmax()

2

In [ ]:
ranarr.min()

10

In [ ]:
ranarr.argmin()

3

## Tömb attribútumok
### shape

A tömb alakja (shape) egész számokból álló értéksor (tuple), amely megadja a tömb méretét az egyes dimenziók mentén.

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# 1-D
arr.shape

(20,)

In [ ]:
np.shape(arr)

(20,)

In [ ]:
# Megjegyzés: 2-D, dupla zárójel [[]]
arr.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [ ]:
arr.reshape(1,20).shape

(1, 20)

In [ ]:
arr.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [ ]:
arr.reshape(20,1).shape

(20, 1)

### ndim
A tömb dimenzióinak száma, a tömb rangja.

In [ ]:
arr.ndim

1

In [ ]:
arr.reshape(1,20).ndim

2

In [ ]:
np.ones((2,2,2,2)).ndim

4

### size
A tömb elemeinek száma.

In [ ]:
np.ones((2,2,2,2)).size

### dtype
A tömb elemeinek típusa (mindegyik elem azonos típusú).

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
sokszínű.dtype

dtype('O')

További információk: [Array attributes](https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes)

___
## NumPy indexelés és kiválasztás

Elemek vagy elemek csoportjának kiválasztása egy tömbből.

In [ ]:
#Tömb (vektor) készítése
vektor = np.arange(0,11)

In [ ]:
#Tömb megjelenítése
vektor

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Zárójeles indexelés és kiválasztás
A tömb egyik vagy néhány elemének kiválasztásának legegyszerűbb módja. Nagyon hasonlít a Python listákhoz.

In [ ]:
#Egy adott indexhez tartozó érték elérése
vektor[5]

5

In [ ]:
#Egy indextartományhoz tartozó értékek elérése
#[start:stop]
vektor[1:6]

array([1, 2, 3, 4, 5])

In [ ]:
vektor[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
vektor[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
vektor[:5]

array([0, 1, 2, 3, 4])

In [ ]:
vektor[-3:-1]

array([8, 9])

In [ ]:
#[start:stop:step]
vektor[1:6:2]

array([1, 3, 5])

In [ ]:
vektor[2::2]

array([ 2,  4,  6,  8, 10])

In [ ]:
# vektor elemeinek megjelenítése fordított sorrendben

In [ ]:
vektor[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 2D tömbök (mátrixok) indexelése

Általános formátum: **`arr_2d[sor][oszlop]`** vagy **`arr_2d[sor,oszlop]`**.

In [ ]:
#Mátrix készítése
mátrix = np.array(([5,10,15],[20,25,30],[35,40,45]))

#A tömb megjelenítése
mátrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexelés
mátrix[1]

array([20, 25, 30])

In [ ]:
# Egyedi elem értékének meghatározása
mátrix[1][0]

20

In [ ]:
# 3. sor 2. elemének kiválasztása
mátrix[2][1]

40

In [ ]:
#Legalsó sor kiválasztása
mátrix[2][:]

array([35, 40, 45])

In [ ]:
mátrix[2,:]

array([35, 40, 45])

In [ ]:
#Középső oszlop kiválasztása

mátrix[0:,:1] #első oszlop
mátrix[0:,1] # 2. oszlop
mátrix[0:,2:] #3.oszlop

array([[15],
       [30],
       [45]])

In [ ]:
# 2D tömb szeletelése (résztömb kiválasztása)
# array([[ 5, 10, 15],
#        [20, 25, 30],
#        [35, 40, 45]])
#A jobb felső sarokban levő 2x2-es mátrix kiválasztása
mátrix[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#A bal alsó sarokban levő 2x2-es mátrix kiválasztása
mátrix[1:,:2]

array([[20, 25],
       [35, 40]])

In [ ]:
mat = np.arange(50).reshape(5,10)

In [ ]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Válasszuk ki a `mat` mátrixból az alábbi résztömböt:
```python
array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])
```

In [ ]:
mat[ 2:, 4:7]

array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])

Válasszuk ki a `mat` mátrixból az alábbi résztömböt:
```python
array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48]])
```

In [ ]:
mat[ ::2, ::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48]])

### Feltételes kiválasztás

In [ ]:
tömb = np.arange(1,11)
tömb

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tömb > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_tömb = tömb>4

In [ ]:
bool_tömb

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
tömb[bool_tömb]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
tömb[tömb>4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# A tömb páros elemeinek kiválasztása
tömb[tömb%2==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
x = 2
tömb[tömb>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tömb[(tömb < x) | (tömb > 3*x)]

array([ 1,  7,  8,  9, 10])

In [ ]:
# A tömb x-nél nagyobb és 3x-nél kisebb elemeinek kiválasztása
x=2
tömb[(x < tömb) & (tömb< 3*x)]
# tömb [x< tömb < 3*x]

array([3, 4, 5])

___
## NumPy műveletek

### Aritmetikai műveletek


In [ ]:
tömb = np.arange(0,10)

In [ ]:
tömb

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tömb + tömb

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
tömb - tömb

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
tömb * tömb

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
tömb + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [ ]:
tömb * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [ ]:
tömb**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
# Tömb értékének nullával való osztása. Warning és nem hiba!!
# Érték helyettesítése: nan

tömb/tömb

<ipython-input-226-fa4430440b7f>:4: RuntimeWarning: invalid value encountered in divide
  tömb/tömb


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/0

ZeroDivisionError: division by zero

In [ ]:
tömb/0

<ipython-input-228-927aca502f9e>:1: RuntimeWarning: divide by zero encountered in divide
  tömb/0
<ipython-input-228-927aca502f9e>:1: RuntimeWarning: invalid value encountered in divide
  tömb/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
# Nullával való osztás. Warning és nem hiba!!
# Érték helyettesítése: inf

1/tömb

<ipython-input-229-5c8eaafe4fc3>:4: RuntimeWarning: divide by zero encountered in divide
  1/tömb


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

### Univerzális függvények

A Numpy számos univerzális függvénnyel rendelkezik: [universal array functions](https://numpy.org/doc/stable/reference/ufuncs.html).

Néhány ezek közül:

In [ ]:
#Négyzetgyökvonás
np.sqrt(tömb)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
#Exponenciális számítás
np.exp(tömb)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
#Maximum érték meghatározása
np.max(tömb) #azonos mint tömb.max()

9

In [ ]:
np.sin(tömb)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(tömb)

<ipython-input-234-a0e0ccb26a85>:1: RuntimeWarning: divide by zero encountered in log
  np.log(tömb)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Numpy objektumok mentése és beolvasása

In [ ]:
mátrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# Mentés 'xxx.npy' néven
np.save('xxx',mátrix)

In [ ]:
# Beolvasás .npy fájlból
npy = np.load('xxx.npy')

In [ ]:
npy

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# Mentés .csv fájlként
np.savetxt('xxx.csv', mátrix)

In [ ]:
# Beolvasás .csv fájlból
csv = np.loadtxt('xxx.csv')

In [ ]:
csv

array([[ 5., 10., 15.],
       [20., 25., 30.],
       [35., 40., 45.]])

## Numpy tömbön és Listán végzett műveletek sebességének összehasonlítása

In [ ]:
lista = list(np.random.randint(0, 1000, 10000000))
tömb = np.array(lista)

In [ ]:
import time
# Lista elemeinek négyzete
start = time.time()
lista_négyzet = [elem**2 for elem in lista]
end = time.time()
lista_idő = end - start
print(lista_idő)

# Tömb elemeinek négyzete

start = time.time()
tömb_négyzet = tömb ** 2
end = time.time()
tömb_idő = end - start
print(tömb_idő)

1.183776617050171
0.03905820846557617


In [ ]:
arány = lista_idő / tömb_idő
print(arány)

30.308011134035723


---
---
***Feladat: BMI index meghatározása***

Az adatok:
|Név    |Kor    |Súly  |Magasság |
|-------|-------|------|---------|
|Anna   |34     |66    |1.65     |
|Zsófia |25     |55    |1.64     |
|János  |30     |86    |1.82     |
|Péter  |32     |76    |1.70     |
|Pál    |20     |68    |1.65     |
|Júlia  |28     |58    |1.70     |

- Készítsen numpy tömböt az adatokkal, majd írassa ki a tömböt.

- Válassza ki a súly oszlopot (index alapján), majd írassa ki az értékeket.

- Válassza ki a magasság oszlopot, majd írassa ki az értékeket.

- Számolja ki a BMI értékeket: BMI = súly / magasság<sup>2</sup>, majd írassa ki 2 tizedesjegyig.

Dokumentáció
- Numpy adattípusok és konverzió: https://numpy.org/doc/stable/user/basics.types.html
- Struktúrált tömbök: https://numpy.org/doc/stable/user/basics.rec.html

In [283]:
import numpy as np
#Készítsen numpy tömböt az adatokkal, majd írassa ki a tömböt.
tömb = np.array((['Név','Kor','Súly','Magasság'],
                  ['Anna',34,66,1.65],
                   ['Zsófia',25,55,1.64],
                    ['János',30,86,1.82],
                     ['Péter',32,76,1.70],
                      ['Pál',20,68,1.65],
                       ['Júlia',28,58,1.70]))
tömb
#Válassza ki a súly oszlopot (index alapján), majd írassa ki az értékeket.
súly = (tömb[0:,2]).reshape(7,1)
súly
#Válassza ki a magasság oszlopot, majd írassa ki az értékeket.
magasság = (tömb[0:,3:])
magasság
#Számolja ki a BMI értékeket: BMI = súly / magasság2, majd írassa ki 2 tizedesjegyig.

BMI = súly / magasság**2

array([['Súly'],
       ['66'],
       ['55'],
       ['86'],
       ['76'],
       ['68'],
       ['58']], dtype='<U32')